Retrofit and Glide
OlyaAnv/Pictures pull request #1
Opened 2023-11-17 19:52 UTC by OlyaAnv

Test

2023-11-19 10:41 UTC, Lyaisan requested changes
- Can we use modules instead of packages for app layers?
- Can we split the code to smaller PRs that covers the dedicated feature? (for ex, creating the modules, preparing the repo for data fetching etc

2023-11-19 10:41 UTC, Lyaisan commented on app/src/main/java/com/example/pictures/ui/scenes/ListFragment.kt
>  //            ItemTouchHelper.LEFT or ItemTouchHelper.RIGHT
We should not have a commented code in the `develop`

2023-11-19 10:41 UTC, Lyaisan commented on app/src/main/java/com/example/pictures/ui/viewmodel/PicturesViewModel.kt
> +                    Log.d("mylog", "ретрофит")
Comments should be written in english, `TAG` should not be abstract and should help to understand where this log was captured. It is better to use `Timber`

2023-11-20 12:38 UTC, OlyaAnv commented on app/src/main/java/com/example/pictures/ui/scenes/ListFragment.kt
>  //            ItemTouchHelper.LEFT or ItemTouchHelper.RIGHT
А что насчет закомментированных избыточных полей в дата классе для запроса данных из сети? Они ведь удобны в случае теоретического расширения проекта?

2023-11-20 12:38 UTC, OlyaAnv commented on app/src/main/java/com/example/pictures/ui/scenes/ListFragment.kt
>  //            ItemTouchHelper.LEFT or ItemTouchHelper.RIGHT
> We should not have a commented code in the `develop`

А что насчет закомментированных избыточных полей в дата классе для запроса данных из сети? Они ведь удобны в случае теоретического расширения проекта?

2023-11-20 12:52 UTC, OlyaAnv commented on app/src/main/java/com/example/pictures/ui/scenes/ListFragment.kt
>  //            ItemTouchHelper.LEFT or ItemTouchHelper.RIGHT
> We should not have a commented code in the `develop`

А ревьюверы могут добавляться в проект сами?

2023-11-20 13:07 UTC, OlyaAnv commented
> * Can we use modules instead of packages for app layers? Please learn and fix the dependencies between the app layers
> * Can we split the code to smaller PRs that covers the dedicated feature? (for ex, creating the modules, preparing the repo for data fetching etc

Имеет ли смысл выносить Retrofit в отдельный модуль в таком маленьком проекте?

2023-12-06 07:58 UTC, closed without merging